"""Add group_id to expense

Revision ID: 9f81ef0dbfb4
Revises: f2e627160591
Create Date: 2026-09-02 12:36:23.582868

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9f81ef0dbfb4'
down_revision = 'f2e627160591'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('expense', schema=None) as batch_op:
        batch_op.add_column(sa.Column('group_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_expense_group_id', 'group', ['group_id'], ['id'])

    with op.batch_alter_table('member', schema=None) as batch_op:
        batch_op.add_column(sa.Column('room_no', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('member', schema=None) as batch_op:
        batch_op.drop_column('room_no')

    with op.batch_alter_table('expense', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('group_id')

    # ### end Alembic commands ###
